# Generated by Django 4.1.7 on 2023-03-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='In_Product',
            fields=[
                ('barcode_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_item', models.CharField(max_length=200)),
                ('product_price', models.ImageField(upload_to='')),
                ('Receipt_date', models.DateField()),
                ('Expected_delivery_date', models.DateField(null=True)),
                ('destination', models.CharField(max_length=200)),
                ('etc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Master_table',
            fields=[
                ('barcode_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_item', models.CharField(max_length=200)),
                ('product_price', models.ImageField(upload_to='')),
                ('Receipt_date', models.DateField()),
                ('Expected_delivery_date', models.DateField()),
                ('destination', models.CharField(max_length=200)),
                ('etc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Out_Product',
            fields=[
                ('barcode_number', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('product_item', models.CharField(max_length=200)),
                ('product_price', models.ImageField(upload_to='')),
                ('Receipt_date', models.DateField()),
                ('Expected_delivery_date', models.DateField()),
                ('destination', models.CharField(max_length=200)),
                ('etc', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price_tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.CharField(max_length=200)),
                ('product_price', models.ImageField(upload_to='')),
            ],
        ),
    ]
