# Generated by Django 4.1.7 on 2023-03-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_dummy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='in_product',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
