# Generated by Django 4.1.7 on 2023-03-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_in_product_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master_table',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='out_product',
            name='product_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price_tag',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
